import { useCallback,useEffect,useRef,useState } from 'react';
import { Bell, Plus, Search, ChevronLeft, ChevronRight, ArrowUpRight, RefreshCw, Sparkles, Check, WifiOff, PanelsTopLeft } from 'lucide-react';
import {api,type Query} from '../features/tasks/api';
import type {Snapshot,Task,TaskDraft,View} from '../features/tasks/types';
import Sidebar,{navItems} from './Sidebar';
import TaskEditor from './TaskEditor';
import TaskList from './TaskList';
import Settings from './Settings';
import ReminderInbox from '../features/reminders/ReminderInbox';

function localDate(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export default function App(){
 const [view,setView]=useState<View>('today');const [date,setDate]=useState(localDate());const [search,setSearch]=useState('');const [searchQuery,setSearchQuery]=useState('');const [priority,setPriority]=useState<number|null>(null);const [page,setPage]=useState(0);
 const [data,setData]=useState<Snapshot|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [editor,setEditor]=useState<{task:Task|null;token:number}|null>(null);const [showSettings,setShowSettings]=useState(false);const [showInbox,setShowInbox]=useState(false);const [notice,setNotice]=useState('');const sequence=useRef(0);const searchRef=useRef<HTMLInputElement>(null);
 const [schedulerError,setSchedulerError]=useState('');const editorGuard=useRef<()=>Promise<boolean>>(async()=>true);const editorToken=useRef(0);
 const openEditor=useCallback(async(task:Task|null)=>{if(!await editorGuard.current())return;editorGuard.current=async()=>true;setEditor({task,token:++editorToken.current});},[]);
 const closeEditor=()=>{editorGuard.current=async()=>true;setEditor(null);};
 const today=data?.today||localDate();const query:Query={view,selected_date:date,search:searchQuery,priority,offset:page*50,limit:50};
 const refresh=useCallback(async()=>{const seq=++sequence.current;try{const result=await api.snapshot({view,selected_date:date,search:searchQuery,priority,offset:page*50,limit:50});if(seq===sequence.current){setData(result);setError('');if(result.scheduler_error!==undefined)setSchedulerError(result.scheduler_error||'');}}catch(e){if(seq===sequence.current)setError(e instanceof Error?e.message:String(e));}finally{if(seq===sequence.current)setLoading(false);}},[view,date,searchQuery,priority,page]);
 useEffect(()=>{const timeout=setTimeout(()=>{setSearchQuery(search);setPage(0);},200);return()=>clearTimeout(timeout);},[search]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),30000);let active=true;const cleanups:(()=>void)[]=[];for(const event of ['tasks_changed','reminders_changed']){api.subscribe(event,()=>void refresh()).then(unlisten=>{if(active)cleanups.push(unlisten);else unlisten();}).catch(()=>{});}return()=>{active=false;clearInterval(timer);cleanups.forEach(f=>f());};},[refresh]);
 useEffect(()=>{let active=true;let cleanup:(()=>void)|undefined;api.subscribe('create_task',()=>openEditor(null)).then(f=>{if(active)cleanup=f;else f();}).catch(()=>{});return()=>{active=false;cleanup?.();};},[openEditor]);
 useEffect(()=>{let active=true;let cleanup:(()=>void)|undefined;api.subscribe('edit_task',value=>{if(value&&typeof value==='object'&&'id' in value)void openEditor(value as Task);}).then(f=>{if(active)cleanup=f;else f();}).catch(()=>{});return()=>{active=false;cleanup?.();};},[openEditor]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();if(!showSettings&&!showInbox)openEditor(null);}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();searchRef.current?.focus();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[openEditor,showSettings,showInbox]);
 useEffect(()=>{let active=true;const cleanups:(()=>void)[]=[];for(const [event,callback] of [['background_error',(value?:unknown)=>setSchedulerError(typeof value==='string'?value:'后台提醒服务异常')],['background_recovered',()=>setSchedulerError('')]] as const){api.subscribe(event,callback).then(f=>{if(active)cleanups.push(f);else f();}).catch(()=>{});}return()=>{active=false;cleanups.forEach(f=>f());};},[]);
 useEffect(()=>{const theme=data?.settings.theme||'system';const media=window.matchMedia('(prefers-color-scheme: dark)');const apply=()=>{document.documentElement.dataset.theme=theme==='system'?(media.matches?'dark':'light'):theme;};apply();media.addEventListener('change',apply);return()=>media.removeEventListener('change',apply);},[data?.settings.theme]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(timer);},[notice]);
 const selectView=(v:View)=>{setView(v);setPage(0);};
 async function save(draft:TaskDraft,scope:'single'|'following'){const owner=editor;await api.save(owner?.task?.id||null,draft,scope);editorGuard.current=async()=>true;setEditor(current=>current?.token===owner?.token?null:current);setNotice('任务已保存');await refresh();}
 async function mutate(action:()=>Promise<unknown>,message?:string){await action();if(message)setNotice(message);await refresh();}
 const title=navItems.find(v=>v.id===view)?.name||'我的任务';
 const descriptions:Record<View,string>={today:'把注意力留给今天，一件一件，慢慢完成。',week:'留一点空间，给这一周的重要安排。',month:'看看这个月，想把时间放在哪里。',date:'提前安排，让每一个截止日期都有准备。',inbox:'先记下来，再为它找到合适的时间。',all:'所有未完成的任务，尽在这里。',overdue:'重新安排节奏，从最重要的一件开始。',completed:'每一件完成的小事，都算数。',trash:'暂时放下的任务，随时可以找回来。'};
 const weekStart=new Date(today+'T12:00:00');weekStart.setDate(weekStart.getDate()-(weekStart.getDay()+6)%7);
 const weekDays=Array.from({length:7},(_,i)=>{const d=new Date(weekStart);d.setDate(d.getDate()+i);return {day:d.getDate(),date:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,name:['一','二','三','四','五','六','日'][i]};});
 return <div className={`app-shell ${editor?'has-editor':''}`}><Sidebar view={view} counts={data?.counts} onView={selectView} onSettings={()=>setShowSettings(true)}/><main className="main-content">
 <header className="topbar"><div className="breadcrumb">我的空间 <span>/</span> <strong>{title}</strong></div><div className="topbar-actions"><button className="button secondary" aria-label="桌面小卡片" onClick={()=>void api.openCard().catch(e=>setError(String(e)))}><PanelsTopLeft size={15}/>小卡片</button><span className="offline-pill"><WifiOff size={13}/>本地模式</span><button className="notification-button icon-button" aria-label="提醒中心" onClick={()=>{setShowInbox(true);void api.markRead().then(refresh).catch(e=>setError(String(e)));}}><Bell size={19}/>{data?.inbox.some(i=>!i.read)&&<i/>}</button></div></header>
 <div className="workspace"><div className="page-heading"><div><span className="eyebrow">{view==='today'?new Date(today+'T12:00:00').toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}):'YOUR PERSONAL SPACE'}</span><h1>{title}<span className="heading-dot"/></h1><p>{descriptions[view]}</p></div><button className="button primary new-task" aria-label="新建任务" onClick={()=>openEditor(null)}><Plus size={18}/>新建任务<span className="shortcut">Ctrl N</span></button></div>
 {view==='today'&&<section className="today-card"><div><span className="card-kicker"><Sparkles size={14}/>今天，也从容一点</span><h2>给重要的事，<br/>留一点专注的时间。</h2><p>无需事事完成，向前一步就很好。</p><div className="hero-stats"><span><b>{data?.counts.today||0}</b> 今日待办</span><span><b>{data?.counts.overdue||0}</b> 待重新安排</span></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="sun-shape"/><div className="floating-note"><span/><span/><div><Check size={17}/><i/></div></div><div className="little-dot"/></div></section>}
 {(view==='today'||view==='week')&&<div className="week-strip"><div className="week-label">本周<span>{new Date(today+'T12:00:00').toLocaleDateString('zh-CN',{month:'long'})}</span></div>{weekDays.map(d=><button key={d.date} className={`day-chip ${d.date===today?'is-today':''}`} aria-label={`查看 ${d.date}`} onClick={()=>{setDate(d.date);selectView('date');}}><span>周{d.name}</span><strong>{d.day}</strong><i/></button>)}</div>}
 {view==='date'&&<label className="date-selection">查看截止日期<input type="date" value={date} onChange={e=>{setDate(e.target.value);setPage(0);}}/></label>}
 {data&&data.counts.overdue>0&&!['overdue','completed','trash'].includes(view)&&<button className="overdue-banner" onClick={()=>selectView('overdue')}><span><span className="status-dot"/>{data.counts.overdue} 项任务已逾期，重新安排一下吧</span><ArrowUpRight size={17}/></button>}
 <div className="list-toolbar"><div className="list-caption"><h2>{search?'搜索结果':view==='completed'?'完成记录':view==='trash'?'回收站':'任务清单'}</h2><span>{data?.total||0}</span>{data?.generation_pending&&<small>正在补齐重复任务…</small>}</div><div className="list-filters"><div className="search-field"><Search size={16}/><input ref={searchRef} aria-label="搜索任务" value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索任务"/>{search&&<button aria-label="清除搜索" onClick={()=>setSearch('')}>×</button>}</div><select aria-label="筛选优先级" value={priority??'all'} onChange={e=>{setPriority(e.target.value==='all'?null:Number(e.target.value));setPage(0);}}><option value="all">全部优先级</option><option value={2}>高优先级</option><option value={1}>普通优先级</option><option value={0}>低优先级</option></select></div></div>
 {schedulerError&&<div className="load-error" role="alert"><p>后台提醒暂时不可用：{schedulerError}。请检查磁盘与权限，程序会继续尝试恢复。</p></div>}
 {error&&<div className="load-error" role="alert"><p>{error}</p><button className="button secondary" onClick={()=>void refresh()}><RefreshCw size={14}/>重试</button></div>}
 {loading?<div className="loading-state" role="status">正在打开你的任务…</div>:data&&<TaskList tasks={data.tasks} overdueIds={data.overdue_ids} view={view} onEdit={task=>{if(task.deleted){setNotice('请先恢复任务再编辑');return;}openEditor(task);}} onToggle={t=>mutate(()=>api.complete(t.id,!t.completed))} onToday={t=>mutate(()=>api.save(t.id,{...t.draft,planned_date:today},'single'),'已安排到今天')} onDelete={t=>mutate(()=>api.remove(t.id,!t.deleted),t.deleted?'任务已恢复':'已移入回收站，可随时恢复')}/>}
 {!['completed','trash'].includes(view)&&data&&<button className="inline-add" onClick={()=>openEditor(null)}><Plus size={18}/><span>添加一件待办</span><kbd>Ctrl N</kbd></button>}
 {data&&data.total>50&&<div className="pagination"><button className="icon-button" aria-label="上一页" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><span>第 {page+1} 页 · 共 {data.total} 项</span><button className="icon-button" aria-label="下一页" disabled={(page+1)*50>=data.total} onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button></div>}
 <footer className="workspace-footer"><span><span className="saved-dot"/>{error?'连接状态待检查':'所有任务保存在程序旁的 data 文件夹'}</span><span>一步一步，拾起秩序。</span></footer></div></main>
 {editor&&<TaskEditor key={editor.token} task={editor.task} today={today} initialDate={view==='today'?today:view==='date'?date:undefined} defaultReminderTime={data?.settings.default_reminder_time} timezone={data?.settings.timezone} onSave={save} onClose={closeEditor} onGuardChange={guard=>{editorGuard.current=guard;}}/>}
 {showSettings&&data&&<Settings settings={data.settings} onClose={()=>setShowSettings(false)} onChanged={refresh}/>}{showInbox&&<ReminderInbox entries={data?.inbox||[]} onClose={()=>setShowInbox(false)}/>}{notice&&<div className="toast" role="status"><Check size={16}/>{notice}</div>}</div>;
}
