import {useCallback,useEffect,useRef,useState} from 'react';
import {Pin,PinOff,ArrowUpRight,X,Plus,Check,CalendarDays,ChevronDown} from 'lucide-react';
import {api} from '../features/tasks/api';
import {emptyDraft,type Snapshot,type Task,type View} from '../features/tasks/types';
import {confirmAction} from './confirm';
import '../styles/card.css';

export default function DesktopCard(){
 const [data,setData]=useState<Snapshot|null>(null),[view,setView]=useState<View>('today'),[pinned,setPinned]=useState(true),[title,setTitle]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState<string[]>([]),[limit,setLimit]=useState(20);
 const sequence=useRef(0);
 const refresh=useCallback(async()=>{const seq=++sequence.current;try{const result=await api.snapshot({view,selected_date:null,search:'',priority:null,offset:0,limit});if(seq===sequence.current)setData(result);}catch(e){if(seq===sequence.current)setError(String(e instanceof Error?e.message:e));}},[view,limit]);
 useEffect(()=>{void refresh();let active=true;const cleanups:(()=>void)[]=[];const timer=setInterval(()=>void refresh(),30000);api.subscribe('tasks_changed',()=>void refresh()).then(f=>{if(active)cleanups.push(f);else f();}).catch(()=>{});return()=>{active=false;clearInterval(timer);cleanups.forEach(f=>f());};},[refresh]);
 useEffect(()=>{api.cardPin().then(setPinned).catch(e=>setError(String(e)));},[]);
 useEffect(()=>{const media=window.matchMedia('(prefers-color-scheme: dark)');const apply=()=>{const theme=data?.settings.theme||'system';document.documentElement.dataset.theme=theme==='system'?(media.matches?'dark':'light'):theme;};apply();media.addEventListener('change',apply);return()=>media.removeEventListener('change',apply);},[data?.settings.theme]);
 async function action(callback:()=>Promise<unknown>){setError('');try{await callback();}catch(e){setError(e instanceof Error?e.message:String(e));}}
 async function add(e:React.FormEvent){e.preventDefault();if(busy||!title.trim())return;setBusy(true);await action(async()=>{const today=data?.today;if(!today)throw new Error('任务尚未加载，请稍后重试');await api.save(null,{...emptyDraft(today,data?.settings.default_reminder_time),title:title.trim(),planned_date:today,due_date:today},'single');setTitle('');await refresh();});setBusy(false);}
 async function toggle(task:Task){if(pending.includes(task.id))return;setPending(p=>[...p,task.id]);await action(async()=>{if(task.draft.subtasks.some(t=>!t.completed)&&!await confirmAction('完成父任务将同时完成所有未完成子任务，是否继续？'))return;await api.complete(task.id,true);await refresh();});setPending(p=>p.filter(id=>id!==task.id));}
 return <main className="desktop-card">
  <header className="card-header"><div className="card-brand" data-tauri-drag-region><span className="card-logo" data-tauri-drag-region><Check size={16}/></span><strong data-tauri-drag-region>拾序</strong><span className="card-drag-hint" data-tauri-drag-region>桌面小卡片</span></div><div className="card-actions"><button className="icon-button" aria-label={pinned?'取消置顶':'置顶卡片'} aria-pressed={pinned} disabled={busy} onClick={()=>{setBusy(true);void action(async()=>setPinned(await api.setCardPin(!pinned))).finally(()=>setBusy(false));}}>{pinned?<Pin size={15}/>:<PinOff size={15}/>}</button><button className="icon-button" aria-label="打开主界面" onClick={()=>void action(api.openMain)}><ArrowUpRight size={17}/></button><button className="icon-button" aria-label="隐藏小卡片" onClick={()=>void action(api.hideCard)}><X size={16}/></button></div></header>
  <section className="card-overview"><div><span>{data?.today||'正在加载'} · {pinned?'已置顶':'自由窗口'}</span><h1>一步一步，完成今天。</h1></div><div className="card-counter"><strong>{data?.counts.today||0}</strong><span>今日待办</span></div></section>
  <div className="card-filter"><label><select aria-label="卡片任务视图" value={view} onChange={e=>{setView(e.target.value as View);setLimit(20);}}><option value="today">本日任务</option><option value="week">本周任务</option><option value="overdue">逾期任务</option><option value="all">全部待办</option></select><ChevronDown size={13}/></label><span>{data?.total||0} 项</span></div>
  {error&&<p className="card-error" role="alert">{error}<button onClick={()=>{setError('');void refresh();}}>重试</button></p>}
  {data?.scheduler_error&&<p className="card-error" role="alert">后台提醒暂时不可用：{data.scheduler_error}</p>}
  <div className="card-task-list">{!data?<p className="card-empty">正在打开任务…</p>:data.tasks.length?data.tasks.map(task=><article className="card-task" key={task.id}><input type="checkbox" aria-label={`完成 ${task.draft.title}`} checked={task.completed} disabled={pending.includes(task.id)} onChange={()=>void toggle(task)}/><div><button className="card-task-title" disabled={pending.includes(task.id)} onClick={()=>void action(()=>api.editInMain(task.id))}>{task.draft.title}</button><div className="card-task-meta">{task.draft.due_date&&<span className={data.overdue_ids.includes(task.id)?'is-overdue':''}><CalendarDays size={11}/>{task.draft.due_date.slice(5)}{data.overdue_ids.includes(task.id)?' · 逾期':''}</span>}{task.draft.priority===2&&<span className="is-overdue">高优先级</span>}{task.draft.subtasks.length>0&&<span>{task.draft.subtasks.filter(s=>s.completed).length}/{task.draft.subtasks.length} 步骤</span>}</div></div></article>):<div className="card-empty"><Check size={25}/><p>{view==='today'?'今天清清爽爽':'没有匹配的待办'}</p><span>写下一件小事，从这里开始。</span></div>}
  {data&&data.total>data.tasks.length&&<button className="card-more" onClick={()=>{if(limit<100)setLimit(n=>Math.min(100,n+20));else void action(api.openMain);}}>{limit<100?'加载更多':'打开主界面查看全部'}</button>}</div>
  <form className="card-quick-add" onSubmit={add}><input aria-label="快速添加任务" placeholder="添加一件今日待办…" maxLength={200} value={title} onChange={e=>setTitle(e.target.value)} disabled={busy}/><button aria-label="添加任务" type="submit" disabled={busy||!title.trim()||!data}><Plus size={18}/></button></form><footer className="card-footer"><span className="saved-dot"/>保存在程序旁的 data 文件夹</footer>
 </main>;
}
