import { useState } from 'react';
import { X, Sun, Moon, Monitor, Download, Upload, Bell, ShieldCheck } from 'lucide-react';
import type {Settings as SettingsType} from '../features/tasks/types';
import {api} from '../features/tasks/api';
import Modal from './Modal';
export default function Settings({settings,onClose,onChanged}:{settings:SettingsType;onClose:()=>void;onChanged:()=>Promise<void>}){
 const [draft,setDraft]=useState({...settings});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const close=()=>{if(busy)return;if(JSON.stringify(draft)!==JSON.stringify(settings)&&!window.confirm('放弃未保存的设置？'))return;onClose();};
 async function run(action:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
 return <Modal label="设置与备份" onClose={close}><header className="panel-heading"><div><span className="eyebrow">MAKE IT YOURS</span><h2>设置与备份</h2></div><button className="icon-button" onClick={close} disabled={busy} aria-label="关闭设置"><X size={20}/></button></header><div className="settings-body">
 <h3>外观</h3><div className="theme-options">{([{id:'light',name:'浅色',icon:Sun},{id:'dark',name:'深色',icon:Moon},{id:'system',name:'跟随系统',icon:Monitor}] as const).map(({id,name,icon:Icon})=><button key={id} disabled={busy} className={`theme-option ${draft.theme===id?'selected':''}`} onClick={()=>setDraft(s=>({...s,theme:id}))}><Icon size={20}/>{name}</button>)}</div>
 <h3>时间与启动</h3><div className="field-pair"><label className="field">应用时区<input list="timezones" value={draft.timezone} onChange={e=>setDraft(s=>({...s,timezone:e.target.value}))}/><datalist id="timezones">{['Asia/Shanghai','Asia/Hong_Kong','Asia/Tokyo','Europe/London','America/New_York','America/Los_Angeles','UTC'].map(v=><option key={v} value={v}/>)}</datalist></label><label className="field">默认提醒时刻<input type="time" value={draft.default_reminder_time.slice(0,5)} onChange={e=>setDraft(s=>({...s,default_reminder_time:e.target.value+':00'}))}/></label></div><label className="setting-toggle"><span>登录 Windows 时启动<span className="helper">后台驻留托盘，保持提醒可用</span></span><input type="checkbox" checked={draft.autostart} onChange={e=>setDraft(s=>({...s,autostart:e.target.checked}))}/></label><p className="helper">关闭窗口会驻留托盘；从托盘退出后，提醒暂停至下次启动。修改时区会重新计算未发送的提醒。</p>
 <h3>通知</h3><button className="button secondary" disabled={busy} onClick={()=>void run(async()=>{await api.testNotification();setMessage('测试通知已提交，请查看 Windows 通知中心。');})}><Bell size={16}/>发送测试通知</button>
 <h3>数据备份</h3><div className="backup-actions"><button className="button secondary" disabled={busy} onClick={()=>void run(async()=>{const path=await api.export('json');if(path)setMessage(`备份已导出：${path}`);})}><Download size={16}/>导出 JSON</button><button className="button secondary" disabled={busy} onClick={()=>void run(async()=>{const path=await api.export('sqlite');if(path)setMessage(`数据库快照已导出：${path}`);})}><Download size={16}/>数据库快照</button><button className="button secondary" disabled={busy} onClick={()=>{if(!window.confirm('恢复将替换当前任务和设置。系统会先备份现有数据库，是否继续选择备份文件？'))return;void run(async()=>{const count=await api.restore();if(count!==null){await onChanged();onClose();}});}}><Upload size={16}/>恢复 JSON 备份</button></div><p className="helper">恢复采用替换模式，不合并数据。恢复前自动保存当前数据库快照。</p><div className="privacy-card"><ShieldCheck size={20}/><p>任务与备份保存在本机，无需账号，也不会上传到服务器。</p></div>
 {error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}</div><footer className="editor-footer"><button className="button secondary" onClick={close} disabled={busy}>关闭</button><button className="button primary" disabled={busy} onClick={()=>void run(async()=>{await api.settings(draft);await onChanged();onClose();})}>{busy?'处理中…':'保存设置'}</button></footer></Modal>;
}
