import { chromium } from '@playwright/test';
import { mkdirSync,writeFileSync } from 'node:fs';
import { spawn } from 'node:child_process';
function answerDialog(answer){return new Promise((resolve,reject)=>{const process=spawn('powershell.exe',['-NoProfile','-NonInteractive','-File','scripts/answer-dialog.ps1','-ProcessId',globalThis.process.env.LOCALTODO_TEST_PID,'-Answer',answer],{windowsHide:true});let errors='';process.stdout.on('data',chunk=>console.log(String(chunk).trim()));process.stderr.on('data',chunk=>errors+=chunk);process.on('exit',code=>code===0?resolve():reject(new Error(errors)));process.on('error',reject);});}
const endpoint=process.env.LOCALTODO_CDP_URL||'http://127.0.0.1:9222';
let browser;for(let i=0;i<30;i++){try{browser=await chromium.connectOverCDP(endpoint);break;}catch{await new Promise(r=>setTimeout(r,1000));}}if(!browser)throw new Error('WebView2 debug endpoint unavailable');
const context=browser.contexts()[0];let page=context.pages()[0];
if(!page)page=await context.waitForEvent('page');
const {expect}=await import('@playwright/test');
const results=[];
const record=(name)=>{results.push({name,passed:true});console.log(`PASS ${name}`);};
await page.waitForLoadState('domcontentloaded');
await expect(page.getByRole('heading',{name:'本日任务',exact:true})).toBeVisible({timeout:30000});
await expect(page.getByText('这里清清爽爽')).toBeVisible();record('native window loads SQLite-backed empty state');
await page.getByRole('button',{name:'新建任务',exact:true}).click();
await page.getByLabel('任务标题',{exact:true}).fill('未保存的草稿');
const cancelDraft=answerDialog('取消操作');
await page.getByRole('button',{name:/添加一件待办/}).click();
await cancelDraft;await page.waitForTimeout(250);
await expect(page.getByLabel('任务标题',{exact:true})).toHaveValue('未保存的草稿');
const discardDraft=answerDialog('继续');
await page.getByRole('button',{name:'关闭编辑',exact:true}).click();
await discardDraft;
await expect(page.getByLabel('任务标题',{exact:true})).toBeHidden();record('switching editor protects unsaved native-window drafts');
await page.getByRole('button',{name:'新建任务',exact:true}).click();
await page.getByLabel('任务标题',{exact:true}).fill('桌面验收 · 提交报告');
await page.getByLabel('优先级',{exact:true}).selectOption('2');
await page.getByLabel('新子任务',{exact:true}).fill('整理资料');await page.getByRole('button',{name:'添加子任务',exact:true}).click();
await page.getByLabel('开启截止提醒',{exact:true}).check();
await page.getByRole('button',{name:'保存任务',exact:true}).click();
await expect(page.getByRole('button',{name:'桌面验收 · 提交报告',exact:true})).toBeVisible();
const task=await page.evaluate(async()=>{const s=await window.__TAURI_INTERNALS__.invoke('snapshot',{query:{view:'all',selected_date:null,search:'桌面验收',priority:null,offset:0,limit:50}});return s.tasks[0];});
if(!task||task.draft.priority!==2||task.draft.subtasks.length!==1||task.draft.reminder_days.join(',')!=='0,1,3')throw new Error('Native Rust save mismatch');record('task editor writes priority subtasks and reminders to Rust SQLite');
const completeParent=answerDialog('继续');
await page.getByRole('checkbox',{name:'完成 桌面验收 · 提交报告',exact:true}).click();
await completeParent;
await expect(page.getByRole('button',{name:'桌面验收 · 提交报告',exact:true})).toBeHidden();
await page.getByRole('button',{name:/已完成/}).click();
await expect(page.getByRole('button',{name:'桌面验收 · 提交报告',exact:true})).toBeVisible();
await page.getByRole('checkbox',{name:'恢复 桌面验收 · 提交报告',exact:true}).click();
await expect(page.getByRole('button',{name:'桌面验收 · 提交报告',exact:true})).toBeHidden();
await page.getByRole('button',{name:/本日任务/}).click();await expect(page.getByRole('button',{name:'桌面验收 · 提交报告',exact:true})).toBeVisible();record('completion and restoration propagate across views');
await page.getByRole('button',{name:'删除 桌面验收 · 提交报告',exact:true}).click();
await page.getByRole('button',{name:/回收站/}).click();await expect(page.getByRole('button',{name:'恢复任务 桌面验收 · 提交报告',exact:true})).toBeVisible();
await page.getByRole('button',{name:'恢复任务 桌面验收 · 提交报告',exact:true}).click();
await page.getByRole('button',{name:/本月任务/}).click();await expect(page.getByRole('button',{name:'桌面验收 · 提交报告',exact:true})).toBeVisible();record('trash restore retains the same task across month view');
await page.getByRole('button',{name:/本日任务/}).click();
mkdirSync('docs/screenshots',{recursive:true});await page.waitForTimeout(4100);await page.screenshot({path:'docs/screenshots/desktop-light.png',fullPage:true});
await page.getByRole('button',{name:'设置与备份',exact:true}).click();await page.getByRole('button',{name:'深色',exact:true}).click();await page.getByRole('button',{name:'保存设置',exact:true}).click();
await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:'docs/screenshots/desktop-dark.png',fullPage:true});record('dark theme saves through desktop settings');
await page.getByRole('button',{name:'新建任务',exact:true}).click();await page.getByLabel('任务标题',{exact:true}).fill('桌面验收 · 每月检查');
await page.getByLabel('重复频率',{exact:true}).selectOption('monthly');await page.getByRole('spinbutton').fill('31');
await page.locator('.editor-body').evaluate(el=>el.scrollTop=0);await page.screenshot({path:'docs/screenshots/desktop-editor.png',fullPage:true});await page.getByRole('button',{name:'保存任务',exact:true}).click();
await page.getByRole('button',{name:/全部待办/}).click();await expect(page.getByRole('button',{name:'桌面验收 · 每月检查',exact:true}).first()).toBeVisible();record('monthly recurrence creates a native instance');
await page.getByLabel('搜索任务',{exact:true}).fill('不存在的任务');await expect(page.getByText('这里清清爽爽')).toBeVisible();record('search filters native query results');
const notification=await page.evaluate(async()=>{try{await window.__TAURI_INTERNALS__.invoke('test_notification');return 'submitted';}catch(e){return {error:e};}});console.log('Notification API:',JSON.stringify(notification));
if(notification!=='submitted')throw new Error('Windows notification submission failed');record('Windows notification API accepts a test notification');
writeFileSync('docs/desktop-smoke-results.json',JSON.stringify({at:new Date().toISOString(),results,notification},null,2));
await browser.close();
